### ISSUE TITLE
Stepup is creating HEAD branch

### ISSUE THREAD

**Issue by rdllopes** [kawamanza/step-up#35]
Kawamanza,

I have a crazy issue with stepup. For no reason, Step-up is creating a HEAD branch when I run stepup version create. Take a look in these "steps":

$ git clone git@bitbucket.org:abrilmdia/metrics.git

$ stepup notes
To perform this operation you need some additional fetch instruction on your git-config file.
May stepup add the missing instruction for you? [yes/no]: yes
         run  git config --add remote.origin.fetch +refs/notes/*:refs/notes/* from "."
         run  git fetch origin from "."
---
$ stepup notes
---
$ stepup version create
         run  git fetch from "."
         run  git tag -a -m "Teste stepup"  HEAD from "."
         run  git push origin refs/tags/ from "."
fatal: remote part of refspec is not a valid name in refs/tags/
        fail  Problems when running `git push origin refs/tags/` (exit status 128)
$ stepup notes
warning: refname 'HEAD' is ambiguous.
warning: refname 'HEAD' is ambiguous.

Best regards,
Rodrigo

**Comment by fpgentil** [comment]
Same problem here with `git version 2.2.0`

**Comment by kawamanza** [comment]
Which version of `step-up` have you installed? There's a missing `<tagname>` option from the `git-tag` command, it is the reason your instruction creates a tag named "HEAD". But I can't reproduce this behavior. Could you give more details about your local environment?

**Comment by fpgentil** [comment]
`$ step-up (0.9.6)`, I can reproduce by running `$ stepup version create`

**Comment by kawamanza** [comment]
I identified the problem when the local commit-ref had already being versioned, so the `stepup version create` command gets an empty information for the next release. Therefore, avoid to run this command twice for the same commit-ref.

The new `step-up (0.9.8)` has the fix for that.
