### ISSUE TITLE
Run over docker

### ISSUE THREAD

**Issue by dgmike** [kawamanza/step-up#47]
The ideal is run over a series of shell files to remove ruby dependency, but it can be temporary resolved by a Dockerfile that install step-up and runs in a simple line command, aka codeclimate cli.

**Comment by kawamanza** [comment]
@dgmike I started to do it on repository [kawamanza/stepup](https://github.com/kawamanza/stepup), but I need to spend some time to transcript the functionalities to bash/shell (or python) language.
