### ISSUE TITLE
StepUp Exception: undefined method `chomp' for nil:NilClass

### ISSUE THREAD

**Issue by tessaroto** [kawamanza/step-up#48]
Fala pessoal, 

Estou tentando usar o stepup no jenkinsfile, mas esta ocorrendo erro:
```
$ stepup version --next-release
StepUp Exception: undefined method `chomp' for nil:NilClass
```

Pelo que vi, após esse commit parou de funcionar:

https://github.com/kawamanza/step-up/commit/336fd8f0dddad1831469498aab7ec0ecc3d2d9e8#diff-16568ff8802b1318fba58b2933a1de8e

Está ocorrendo na linha :
`tag = STDIN.first.chomp`

Por enquanto estou usando a versão 0.9.8, o erro não ocorre nela.

abs

**Comment by kawamanza** [comment]
Olá, identifiquei essa falha e vou tratar. Se quiser resolver por hora,
force a versão 0.9.14 da gem no seu fluxo CI/CD.

Em ter, 24 de jul de 2018 20:42, tessaroto <notifications@github.com>
escreveu:

**Comment by kawamanza** [comment]
@tessaroto Efetuei a correção disso. Está disponível na versão 0.9.16 da gem.

Caso queira, pode usar a versão docker do utilitário pelo `kawamanza/stepup-cli:0.9.16` (mais detalhes em https://github.com/kawamanza/docker-stepup-cli).

**Comment by tessaroto** [comment]
Boaa @kawamanza!! Vou fazer um teste a noite :D

Ah a Mineiro (Leandro Miserani) te mandou um abs

Valeuu !!

**Comment by kawamanza** [comment]
Opa, Manda outro! hehehe. Mundo pequeno.
